name: clubhouse
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 # cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  cloud_functions: ^3.2.16
  provider: ^6.0.3
  pinput: ^2.2.10
  country_code_picker: ^2.0.2
  country_pick_screen: ^2.0.2
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  modal_progress_hud_nsn: ^0.2.1-nullsafety-1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  flutter_contacts: ^1.1.4
  permission_handler: ^9.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Fredoka One
      fonts:
         - asset: fonts/FredokaOne-Regular.ttf

